//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aoc.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 191
        ///192
        ///201
        ///205
        ///206
        ///203
        ///188
        ///189
        ///199
        ///206
        ///224
        ///230
        ///233
        ///232
        ///260
        ///257
        ///258
        ///259
        ///251
        ///233
        ///236
        ///237
        ///238
        ///241
        ///242
        ///243
        ///250
        ///259
        ///251
        ///255
        ///263
        ///265
        ///266
        ///259
        ///265
        ///260
        ///267
        ///270
        ///271
        ///284
        ///286
        ///301
        ///302
        ///304
        ///309
        ///333
        ///335
        ///342
        ///350
        ///349
        ///342
        ///343
        ///345
        ///346
        ///331
        ///332
        ///317
        ///324
        ///328
        ///327
        ///332
        ///320
        ///340
        ///341
        ///344
        ///353
        ///361
        ///372
        ///376
        ///387
        ///397
        ///433
        ///431
        ///432
        ///436
        ///435
        ///449
        ///460
        ///474
        ///476
        ///483
        ///490
        ///487
        ///488
        ///495
        ///500
        ///511
        ///531
        ///537
        ///525
        ///503
        ///506
        ///515
        ///517
        ///518
        ///517
        ///514
        ///516
        ///521
        ///515
        ///516
        ///517
        ///52 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string day1_input {
            get {
                return ResourceManager.GetString("day1_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die forward 8
        ///forward 3
        ///down 8
        ///forward 4
        ///down 2
        ///down 4
        ///down 8
        ///down 4
        ///down 7
        ///up 4
        ///down 6
        ///down 2
        ///forward 7
        ///down 5
        ///down 7
        ///down 5
        ///forward 8
        ///forward 4
        ///forward 3
        ///down 4
        ///forward 2
        ///up 3
        ///up 6
        ///forward 7
        ///down 4
        ///down 2
        ///forward 7
        ///up 3
        ///forward 8
        ///down 4
        ///down 6
        ///forward 3
        ///forward 9
        ///down 9
        ///down 6
        ///forward 8
        ///up 8
        ///forward 3
        ///down 8
        ///down 4
        ///forward 7
        ///forward 3
        ///up 9
        ///down 8
        ///forward 7
        ///forward 5
        ///forward 3
        ///down 1
        ///down 4
        ///forward 1
        ///down 6
        ///forward 9
        ///up 2
        ///forward 3
        ///down 2
        ///down 1
        ///up 5
        ///dow [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string day2_input {
            get {
                return ResourceManager.GetString("day2_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 110011101111
        ///011110010111
        ///101010111001
        ///110011100110
        ///110010000101
        ///000111001111
        ///001111110011
        ///100000111010
        ///101010000110
        ///001000100011
        ///110000000100
        ///000100110000
        ///010010101110
        ///101110111101
        ///100000100111
        ///111011010111
        ///001101010010
        ///010010001111
        ///010101100001
        ///111001101101
        ///110110000011
        ///000110111111
        ///111111100010
        ///110010101011
        ///010011100100
        ///110011010010
        ///100001111010
        ///000101000110
        ///110001000111
        ///110110000001
        ///101011010110
        ///101001011010
        ///100101000110
        ///101010110001
        ///111000110110
        ///111000001111
        ///01011110 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string day3_input {
            get {
                return ResourceManager.GetString("day3_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 37,60,87,13,34,72,45,49,61,27,97,88,50,30,76,40,63,9,38,67,82,6,59,90,99,54,11,66,98,23,64,14,18,4,10,89,46,32,19,5,1,53,25,96,2,12,86,58,41,68,95,8,7,3,85,70,35,55,77,44,36,51,15,52,56,57,91,16,71,92,84,17,33,29,47,75,80,39,83,74,73,65,78,69,21,42,31,93,22,62,24,48,81,0,26,43,20,28,94,79
        ///
        ///66 78  7 45 92
        ///39 38 62 81 77
        /// 9 73 25 97 99
        ///87 80 19  1 71
        ///85 35 52 26 68
        ///
        ///47 38 84 53 16
        ///66  3 63 92 94
        ///71 41 59  1 87
        ///17 67 62 73 33
        ///69 12 26 82 55
        ///
        ///89 94 65 57  6
        ///27 77 60 19 83
        ///72 58  0 29 91
        ///33 75 5 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string day4_input {
            get {
                return ResourceManager.GetString("day4_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 959,103 -&gt; 139,923
        ///899,63 -&gt; 899,53
        ///591,871 -&gt; 364,644
        ///739,913 -&gt; 310,484
        ///460,309 -&gt; 460,705
        ///351,389 -&gt; 351,837
        ///420,55 -&gt; 420,541
        ///916,520 -&gt; 382,520
        ///136,604 -&gt; 295,604
        ///343,59 -&gt; 142,59
        ///951,206 -&gt; 806,206
        ///984,950 -&gt; 61,27
        ///739,388 -&gt; 988,388
        ///374,370 -&gt; 644,370
        ///403,504 -&gt; 798,899
        ///943,535 -&gt; 229,535
        ///149,227 -&gt; 583,661
        ///62,126 -&gt; 62,352
        ///131,391 -&gt; 131,717
        ///254,944 -&gt; 254,220
        ///572,111 -&gt; 572,47
        ///336,249 -&gt; 830,743
        ///898,858 -&gt; 203,163
        ///203,320 -&gt; 825,942
        ///19,318 -&gt; 19,120
        ///740,432 -&gt; 740,39
        ///591,3 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string day5_input {
            get {
                return ResourceManager.GetString("day5_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3,5,3,1,4,4,5,5,2,1,4,3,5,1,3,5,3,2,4,3,5,3,1,1,2,1,4,5,3,1,4,5,4,3,3,4,3,1,1,2,2,4,1,1,4,3,4,4,2,4,3,1,5,1,2,3,2,4,4,1,1,1,3,3,5,1,4,5,5,2,5,3,3,1,1,2,3,3,3,1,4,1,5,1,5,3,3,1,5,3,4,3,1,4,1,1,1,2,1,2,3,2,2,4,3,5,5,4,5,3,1,4,4,2,4,4,5,1,5,3,3,5,5,4,4,1,3,2,3,1,2,4,5,3,3,5,4,1,1,5,2,5,1,5,5,4,1,1,1,1,5,3,3,4,4,2,2,1,5,1,1,1,4,4,2,2,2,2,2,5,5,2,4,4,4,1,2,5,4,5,2,5,4,3,1,1,5,4,5,3,2,3,4,1,4,1,1,3,5,1,2,5,1,1,1,5,1,1,4,2,3,4,1,3,3,2,3,1,1,4,4,3,2,1,2,1,4,2,5,4,2,5,3,2,3,3,4,1,3,5,5,1,3,4,5,1,1,3,1,2,1,1,1,1,5,1, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string day6_input {
            get {
                return ResourceManager.GetString("day6_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,78,78,1006,298,320,1021,308,639,76,65,531,302,936,125,502,481,793,369,213,25,158,1423,1387,996,519,138,16,1348,1390,957,24,67,126,35,576,333,788,1707,845,278,732,512,1187,1203,153,1126,15,297,200,43,454,901,176,994,1268,1833,195,1,1705,373,175,417,410,511,63,244,136,552,433,8,347,546,1167,8 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string day7_input {
            get {
                return ResourceManager.GetString("day7_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dbc gfecab afcdg dfebcag bd dgbe bcaeg dcefab ecgadb agcbd | acdgb gbcda gdecfba bacge
        ///bacdegf aefbdc ebf fdbcag edbfa gdaeb acfdb cdegbf face fe | ebf ecdabf fcbad afcdbg
        ///cabgde gd becgfd dgfe cebgf gfdeacb fdbac bcgaef bgdfc gdc | cbfad dg dgef ecfbdg
        ///adecgf egfdc cgeadb adbfce dafg bcfeg dge dg fadec dcbegaf | dg dcegf cdgafe gbacfed
        ///badeg gdbfcea acgef fgdc bgcaef cd ebcfda gadce edcgaf edc | dce efcga dbgea dc
        ///bgfec dbfgec ebgafc afegcdb fca af cgdabf aegf badce cfabe | caf ebacf bafgec cbfeag
        ///be [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string day8_input {
            get {
                return ResourceManager.GetString("day8_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string day9_input {
            get {
                return ResourceManager.GetString("day9_input", resourceCulture);
            }
        }
    }
}
