//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 191
        ///192
        ///201
        ///205
        ///206
        ///203
        ///188
        ///189
        ///199
        ///206
        ///224
        ///230
        ///233
        ///232
        ///260
        ///257
        ///258
        ///259
        ///251
        ///233
        ///236
        ///237
        ///238
        ///241
        ///242
        ///243
        ///250
        ///259
        ///251
        ///255
        ///263
        ///265
        ///266
        ///259
        ///265
        ///260
        ///267
        ///270
        ///271
        ///284
        ///286
        ///301
        ///302
        ///304
        ///309
        ///333
        ///335
        ///342
        ///350
        ///349
        ///342
        ///343
        ///345
        ///346
        ///331
        ///332
        ///317
        ///324
        ///328
        ///327
        ///332
        ///320
        ///340
        ///341
        ///344
        ///353
        ///361
        ///372
        ///376
        ///387
        ///397
        ///433
        ///431
        ///432
        ///436
        ///435
        ///449
        ///460
        ///474
        ///476
        ///483
        ///490
        ///487
        ///488
        ///495
        ///500
        ///511
        ///531
        ///537
        ///525
        ///503
        ///506
        ///515
        ///517
        ///518
        ///517
        ///514
        ///516
        ///521
        ///515
        ///516
        ///517
        ///52 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day1_input {
            get {
                return ResourceManager.GetString("day1_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 8
        ///forward 3
        ///down 8
        ///forward 4
        ///down 2
        ///down 4
        ///down 8
        ///down 4
        ///down 7
        ///up 4
        ///down 6
        ///down 2
        ///forward 7
        ///down 5
        ///down 7
        ///down 5
        ///forward 8
        ///forward 4
        ///forward 3
        ///down 4
        ///forward 2
        ///up 3
        ///up 6
        ///forward 7
        ///down 4
        ///down 2
        ///forward 7
        ///up 3
        ///forward 8
        ///down 4
        ///down 6
        ///forward 3
        ///forward 9
        ///down 9
        ///down 6
        ///forward 8
        ///up 8
        ///forward 3
        ///down 8
        ///down 4
        ///forward 7
        ///forward 3
        ///up 9
        ///down 8
        ///forward 7
        ///forward 5
        ///forward 3
        ///down 1
        ///down 4
        ///forward 1
        ///down 6
        ///forward 9
        ///up 2
        ///forward 3
        ///down 2
        ///down 1
        ///up 5
        ///dow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day2_input {
            get {
                return ResourceManager.GetString("day2_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110011101111
        ///011110010111
        ///101010111001
        ///110011100110
        ///110010000101
        ///000111001111
        ///001111110011
        ///100000111010
        ///101010000110
        ///001000100011
        ///110000000100
        ///000100110000
        ///010010101110
        ///101110111101
        ///100000100111
        ///111011010111
        ///001101010010
        ///010010001111
        ///010101100001
        ///111001101101
        ///110110000011
        ///000110111111
        ///111111100010
        ///110010101011
        ///010011100100
        ///110011010010
        ///100001111010
        ///000101000110
        ///110001000111
        ///110110000001
        ///101011010110
        ///101001011010
        ///100101000110
        ///101010110001
        ///111000110110
        ///111000001111
        ///01011110 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day3_input {
            get {
                return ResourceManager.GetString("day3_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37,60,87,13,34,72,45,49,61,27,97,88,50,30,76,40,63,9,38,67,82,6,59,90,99,54,11,66,98,23,64,14,18,4,10,89,46,32,19,5,1,53,25,96,2,12,86,58,41,68,95,8,7,3,85,70,35,55,77,44,36,51,15,52,56,57,91,16,71,92,84,17,33,29,47,75,80,39,83,74,73,65,78,69,21,42,31,93,22,62,24,48,81,0,26,43,20,28,94,79
        ///
        ///66 78  7 45 92
        ///39 38 62 81 77
        /// 9 73 25 97 99
        ///87 80 19  1 71
        ///85 35 52 26 68
        ///
        ///47 38 84 53 16
        ///66  3 63 92 94
        ///71 41 59  1 87
        ///17 67 62 73 33
        ///69 12 26 82 55
        ///
        ///89 94 65 57  6
        ///27 77 60 19 83
        ///72 58  0 29 91
        ///33 75 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day4_input {
            get {
                return ResourceManager.GetString("day4_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,9 -&gt; 5,9
        ///8,0 -&gt; 0,8
        ///9,4 -&gt; 3,4
        ///2,2 -&gt; 2,1
        ///7,0 -&gt; 7,4
        ///6,4 -&gt; 2,0
        ///0,9 -&gt; 2,9
        ///3,4 -&gt; 1,4
        ///0,0 -&gt; 8,8
        ///5,5 -&gt; 8,2
        ///.
        /// </summary>
        internal static string day5_input {
            get {
                return ResourceManager.GetString("day5_input", resourceCulture);
            }
        }
    }
}
